sign: Sign key for JWT
winbind: "Will call /domaininfo/GetUserId with userName query to get the user's id info"
masterToken: "Access token of all users"

authEnabled:
  wechat: 1
  microsoft: 1


activeDirectory:
  tenant: "***************************"
  clientId: "***************************"
  clientSecret: "***************************"



wechat:
  appId: "***************************"
  appSecret: ""***************************""


domain: "http://atlas02.sigsus.cn"
casUrl: "http://atlas02.sigsus.cn/cas"

administrators:

  - tony@hotmail.com

  - tom@apulis.com

  - tomas@apulis.com

  - jeck.chen@apulis.com

clusters:
  atlas:
      restfulapi: "http://atlas02.sigsus.cn/apis"
      title: Grafana-endpoint-of-the-cluster
      workStorage: /dlwsdata/work
      dataStorage: /dlwsdata/storage
      grafana: "http://atlas02.sigsus.cn/endpoints/grafana/"
      prometheus: http://atlas02.sigsus.cn:9091
userGroup:
  type: custom
  domain: "http://atlas02.sigsus.cn"
  backEndPath: /custom-user-dashboard-backend
  frontEndPath: /custom-user-dashboard
