job_info:
  backup_path: /mnt/fuse
  support_cluster: atlas
  work_path: /mntdlws/work/
  data_path: /mntdlws/storage/
  jobfiles_path: /mntdlws/jobfiles/

job_template:
  - template_Name: Test_mindspore_8npu
    ai_platform: mindspore0.5.0
    node_num: 1
    device_type: npu
    device_num: 8
    image: apulistech/mindspore:0.3.0-withtools
    Cmd: sudo -E bash -c 'cd /data/resnet50_cifar10/ && mkdir -p /var/log/npu/conf/slog/ && cp slog.conf /var/log/npu/conf/slog/ && ./run_8p.sh &&sleep infinity'
    
  - template_Name: test_tensorflow_8npu
    ai_platform: tensorflow1.15
    node_num: 1
    image: apulistech/tensorflow:1.15-withtools
    device_type: npu
    device_num: 8
    cmd: "sudo -E bash -c 'source /pod.env && cp -r /data/Resnet50_HC /tmp/ && pip install sympy && cd /tmp/Resnet50_HC/  && ./run_8p.sh && sleep infinity'"

  - template_Name: cpu-test-withtools
    ai_platform: pytorch
    node_num: 1
    device_type: cpu
    device_num: 0
    image: ubuntu:18.04
    Cmd: sleep 30m

  - template_Name: gpu
    ai_platform: pytorch
    device_type: gpu
    device_num: 1
    image: apulistech/cuda:10.0-withtools
    Cmd: sudo bash -c "source /root/anaconda3/bin/deactivate && conda activate open-mmlab && cd /root/pytorch_samples/mnist/ && python main.py --epochs 5"
  		
  - template_Name: horovod
    ai_platform: horovod
    node_num: 1
    device_type: gpu
    device_num: 1
    image: apulistech/horovod
    Cmd: horovodrun -np 16 -hostfile /job/ib_config  -p $DLWS_SD_worker0_SSH_PORT --network-interface ib0 python /data/tensorflow2_keras_mnist.py  ./tensorboard/${DLWS_JOB_ID}/logs/ && sleep 10m
  		
  - template_Name: test_tensorflow_8npu
    ai_platform: tensorflow1.15
    node_num: 1
    device_type: npu
    device_num: 8
    image: apulistech/tensorflow:1.15-withtools
    Cmd: sudo -E bash -c 'source /pod.env && cp -r /data/Resnet50_HC /tmp/ && pip install sympy && cd /tmp/Resnet50_HC/  && ./run_8p.sh && sleep infinity'
  
  - template_Name: test_tensorflow_16npu
    ai_platform: tensorflow1.15
    node_num: 2
    device_type: npu
    device_num: 16
    image: apulistech/tensorflow:1.15-withtools
    Cmd: sudo -E bash -c 'source /pod.env && cp -r /data/Resnet50_HC /tmp/ && pip install sympy && cd /tmp/Resnet50_HC/  && ./run_d.sh && sleep infinity'	
  
  - template_Name: npu_test_8npu
    ai_platform: mindspore0.5.0
    node_num: 1
    device_type: cpu
    device_num: 8
    image: apulistech/mindspore:0.3.0-withtools
    Cmd: sudo -E bash -c ' cd /data/resnet50_cifar10/ && ./run_8p.sh &&sleep infinity'
    
  - template_Name: test_mindspore_16npu
    ai_platform: mindspore0.5.0
    node_num: 2
    device_type: npu
    device_num: 16
    image: apulistech/mindspore:0.3.0-withtools
    Cmd: sudo -E bash -c 'source /pod.env && cd /data/resnet50_cifar10/ && mkdir -p /var/log/npu/conf/slog/ && cp slog.conf /var/log/npu/conf/slog/ && ./run_d.sh && sleep infinity'

  - template_Name: test_mindspore_8npu
    ai_platform: mindspore0.5.0
    node_num: 1
    device_type: npu
    device_num: 8
    image: apulistech/mindspore:0.3.0-withtools
    Cmd: sudo -E bash -c 'cd /data/resnet50_cifar10/ && mkdir -p /var/log/npu/conf/slog/ && cp slog.conf /var/log/npu/conf/slog/ && ./run_8p.sh &&sleep infinity'
  		
  
  	
  
  		
  