version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
loglevel: debug # deprecated: use "log"
storage:
  filesystem:
    rootdirectory: /DockerRegistry/
    maxthreads: 100
  inmemory:  # This driver takes no parameters
  delete:
    enabled: true
  redirect:
    disable: false
  cache:
    blobdescriptor: redis
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false

http:
  addr: localhost:5000
  prefix: /registry/
  secret: apulisDocker
  relativeurls: false
  draintimeout: 60s
  debug:
    addr: localhost:5001
    prometheus:
      enabled: true
      path: /metrics
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false
redis:
  addr: localhost:6379
  password: apulisRedis@18D
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
  file:
    - file: /DockerRegistry/config.yaml
      interval: 10s
  tcp:
    - addr: localhost:6379
      timeout: 3s
      interval: 10s
      threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
  username: [apulistech]
  password: [Yitong#123]
compatibility:
  schema1:
    signingkeyfile: no
    enabled: true